### ISSUE TITLE
AttributeError: 'GeneInfo' object has no attribute 'genic_regions'

### ISSUE THREAD

**Issue by skudashev** [ablab/platform_comparison#1]
Hello, thank you for the great paper and scripts, 

I have been trying to use you assign_reads_to_isoforms script, but get an AttributeError
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/platform_comparison/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/platform_comparison/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/ei/projects/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/data/tools/platform_comparison/src/dataset_processor.py", line 80, in assign_reads_in_parallel
    assignment_storage = alignment_processor.process(intron_info_printer)
  File "/ei/projects/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/data/tools/platform_comparison/src/alignment_processor_simple.py", line 52, in process
    self.process_single_file(b, intron_printer)
  File "/ei/projects/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/data/tools/platform_comparison/src/alignment_processor_simple.py", line 64, in process_single_file
    for genic_region in self.gene_info.genic_regions:
AttributeError: 'GeneInfo' object has no attribute 'genic_regions'  
```
"""
I used a gencode gtf to create the database. 
```
python tools/platform_comparison/gtf2db.py --gtf gencode.gtf --complete_genedb --output gencode.v40.annotation_sequin.db
python tools/platform_comparison/assign_reads_to_isoforms.py --reference gencode.fa --genedb gencode.v40.annotation_sequin.db \
--data_type nanopore --matching_strategy default --threads 20 --intron_stats --sqanti_output \
--bam alignments/2022-07-19-2pass_primaryonly.sorted.bam --output assign_reads_out
```
Would really appreciate some advice. 

Best wishes, 
Sofia

**Comment by andrewprzh** [comment]
Dear Sofia

Thank you for your interest in our scripts. We have re-implemented all scripts in a single user-friendly tool that can assign reads to isoforms, quantify transcripts and discover novel transcripts models: https://github.com/ablab/IsoQuant

Let me know if this works!

Best
Andrey

**Comment by skudashev** [comment]
Thank you, Andrey!
